### PR TITLE
Use default ocamlformat margin

### PR DESCRIPTION
**Pull request by NathanReb**
We used to have a custom `margin=100` in the config file.

### CODE REVIEW

**Comment by NathanReb** [comment]
Probably wise to merge the outstanding PRs first!

**Comment by emillon** [comment]
it's probably possible to autorebase using something like `git checkout --ours .; git checkout --theirs .ocamlformat; dune build @fmt`

**Comment by emillon** [comment]
I just did that, the process is:

- checkout PR branch
- `git rebase main`
- for each commit with a conflict:
  + confirm deletions if any (`git rm` whenever there's a "deleted by us", ie the conflict is between deleting and reformatting the file)
  + `git checkout --theirs .` (checkout the version from the PR)
  + `dune build @fmt --auto-promote`
  + `git add .`
  + `git rebase --continue`

Probably automatable as a `git rebase -x` command but that can be done by hand.

**Comment by NathanReb** [comment]
I guess we can go ahead and merge then!

**Review by emillon — APPROVED** [review]

**Pull request merged**
