### PR TITLE
Upgrade to self 0.3.0

### PR DESCRIPTION
**Pull request by NathanReb**
This PR upgrades our lockfile and get us to use opam-monorepo.0.3.0.

Not much to note regarding the lockfile.

A warning introduced in opam-monorepo.0.3.0 triggers on our tests because there are duplicate pkg definitions in there. I renamed the opam files that were causing troubles and tried giving them more meaningful names.

### CODE REVIEW

**Comment by NathanReb** [comment]
I'll keep this as draft until `0.3.0` is actually released!

We can use this branch to test the CI! CC @Leonidas-from-XIV

**Comment by Leonidas-from-XIV** [comment]
The OCaml CI deployed with the changes from [ocaml-ci#445](https://github.com/ocurrent/ocaml-ci/pull/445). Can you push something to this branch to see it work?

**Comment by NathanReb** [comment]
I pushed but it seems to have met little success

**Comment by Leonidas-from-XIV** [comment]
The CI needs to be redeployed with my fix which pins opam-monorepo inside the Docker container, not outside of it.

**Review by Leonidas-from-XIV — APPROVED** [review]
Looks like everything is in place! Time to :boat: it

**Pull request merged**
