### PR TITLE
Support OCaml 4.12

### PR DESCRIPTION
**Pull request by TheLortex**
No changes happen in opam-monorepo, but the vendored dependencies had to be updated, notably `astring` and `fpath`. 
`opam-format.2.1.0~beta4` has a breaking changes so we're locked on `2.1.0~beta2` for now.

`fpath.0.7.3` has to be added in dune-universe/opam-overlays for the lock to be reproducible: https://github.com/dune-universe/opam-overlays/pull/85

### CODE REVIEW

**Comment by TheLortex** [comment]
EDIT: forced pushed to have `ocaml = 4.12.0` instead of `ocaml = 4.12.1` in the lockfile for the CI. But it doesn't seem to work.

**Comment by avsm** [comment]
Having a more flexible patch version results in this bug in ocaml-ci, so reverting that for now https://github.com/ocurrent/ocaml-ci/issues/339

**Comment by avsm** [comment]
@TheLortex I'm seeing this diff to your PR when i monorepo pull -- do you have an override to `num`?

```
--- a/duniverse/num/src/config/dune
+++ b/duniverse/num/src/config/dune
@@ -4,5 +4,4 @@
 
 (rule
   (targets arch cflags)
-  (deps discover.exe)
   (action (run ./discover.exe)))
```

**Comment by NathanReb** [comment]
> `opam-format.2.1.0~beta4` has a breaking changes so we're locked on 2.1.0~beta2 for now.

That's good to know, I'll look into this as it is quite important that we're compatible with the latest opam libraries!

**Comment by TheLortex** [comment]
> @TheLortex I'm seeing this diff to your PR when i monorepo pull -- do you have an override to `num`?

That's my bad, I used an old version of `opam-overlays` !

**Comment by avsm** [comment]
Thanks! Just checking you didn't have an override.

**Comment by avsm** [comment]
I pushed a couple of fixes to:

- support latest opam-file-format to remove the beta2 constraint on opam-libs (c6a73d0f7bb5d9d6698a72a135268d8b0631d615)
- parse depopts as well when looking for dune compatibility to work with opam-file-format (c6a73d0f7bb5d9d6698a72a135268d8b0631d615)

If you could take a look at those to check they're ok @TheLortex @NathanReb, we can merge this and upgrade to latest ocamlformat (0.15 doesnt install in OCaml 4.12)

**Comment by TheLortex** [comment]
Looks good to me ! Indeed the `depopts` change will allow us to have `"opam-file-format" {= "2.1.2"}`

**Comment by avsm** [comment]
I'm just fixing the CI ahead of merging this.

**Comment by avsm** [comment]
Tezos needs this now as well: https://gitlab.com/tezos/tezos/-/issues/1399

**Comment by NathanReb** [comment]
> Tezos needs this now as well: https://gitlab.com/tezos/tezos/-/issues/1399

Latest released opam-monorepo is compatible with 4.12! I'm closing this!

**Comment by avsm** [comment]
Amazing, thanks @NathanReb :)

**Comment by NathanReb** [comment]
You even have 4.13 support coming with #181

**Pull request closed without merging**
