### PR TITLE
Upgrade ocamlformat to 0.20.1

### PR DESCRIPTION
**Pull request by NathanReb**

### CODE REVIEW

**Comment by emillon** [comment]
I think that ocaml-ci is hitting https://github.com/ocurrent/ocaml-ci/issues/398 again.

**Comment by NathanReb** [comment]
@Leonidas-from-XIV should we go ahead and merge this or would you rather wait for the CI to be fixed?

**Comment by Leonidas-from-XIV** [comment]
@NathanReb Let's merge now. We'll have to do that sooner or later anyway and fixing the CI will fix all our projects at the same time.

**Comment by NathanReb** [comment]
Actually now that I think about it, won't it be annoying not to be able to trust the CI status? This is easy to redo on top of any point in the history either way and there's nothing inherently wrong with `0.19` is there?

**Comment by NathanReb** [comment]
Ok let's close this then, I'll re-open once the CI is fixed!

**Pull request closed without merging**
